### PR TITLE
use ember-auto-import to load rest-js v2.x

### PR DESCRIPTION
**Pull request by jgravois**
relies on 
- [x] https://github.com/Esri/torii-provider-arcgis/pull/66

* use ember-auto-import instead of vendor shims
* bump to rest-js v2.x (as peerDependencies instead of dependencies)
* remove group sharing methods and import them from rest-js instead
* confirmed working in dummy app (with torii yarn linked)

### CODE REVIEW

**Comment by jgravois** [comment]
if you want me to tack on another commit that tackles #147, just say the word.

**Comment by tomwayson** [comment]
Yeah we should address #147 since we'll be bumping major.

**Comment by tomwayson** [comment]
Looks like we need to add node_modules to .eslintignore here too, as for the [rest of the lint errors](https://travis-ci.org/Esri/ember-arcgis-portal-services/jobs/527492740), I wonder why they don't also show up in the ember lint "tests"?

**Comment by jgravois** [comment]
> Yeah we should address #147 since we'll be bumping major.

done in 2677a49

Looks like we need to add node_modules to .eslintignore here too

done in 2677a49

> as for the rest of the lint errors, I wonder why they don't also show up in the ember lint "tests"?

not sure, but i amended the npm script (and travis commands) to ensure that the code is linted each and every time `npm test` is run.

**Pull request merged**
